name: Build & Test

on:
  pull_request:
    branches: [ 'master' ]

env:
  IMAGE_NAME_FRONTEND_TAG: ${{ github.repository }}/frontend:test
  IMAGE_NAME_BACKEND_TAG: ${{ github.repository }}/backend:test
  DATABASE_HOST: 127.0.0.1
  DATABASE_PORT: 3306
  DATABASE: bildungsportal
  DATABASE_USER: root
  DATABASE_PASSWORD: ""
  RABBITMQ_PORT: 5672
  JWT_SECRET: secret
  CYPRESS_accessToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZvb0BleGFtcGxlLmNvbSIsImlhdCI6MCwiZXhwIjo5OTk5OTk5OTk5OX0.iJ9GWyGeQypTDqiTwgxlm9YIMXzyyUJk4zLzAkx0FSs
  CYPRESS_baseUrl: http://localhost:3000
  REACT_APP_BACKEND: "http://localhost:8080"

jobs:
  buildBackend:
    name: '[BACKEND] Build & Test '
    runs-on: ubuntu-latest
    steps:
      - name: Backend Env to Lowercase
        run: |
          echo "BACKEND_TAG=${IMAGE_NAME_BACKEND_TAG,,}">>${GITHUB_ENV}

      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Build Image
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          load: true
          tags: ${{ env.BACKEND_TAG }}

  buildFrontend:
    name: '[FRONTEND] Build & Test'
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: bildungsportal
          MYSQL_HOST: 127.0.0.1
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Frontend Env to Lowercase
        run: |
          echo "FRONTEND_TAG=${IMAGE_NAME_FRONTEND_TAG,,}">>${GITHUB_ENV}
      
      - name: "Setup Java 18"
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '18'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current

      - name: "Build Backend with Gradle"
        run: |
          cd ./backend
          gradle build --no-daemon -PisIntegrationTest=true

      - name: Apply MySQL File to Database
        run: |
          mysql -h 127.0.0.1 -P 3306 -u root bildungsportal < ./test/db/init.sql 
        
      - name: Change auth plugin for root
        run: |
          mysql -h 127.0.0.1 -P 3306 -u root -e "ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY '';FLUSH PRIVILEGES;"
    
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Start Backend
        run: |
          cd ./backend
          java -jar ./build/libs/backend-0.0.1-SNAPSHOT.jar &

      - name: Wait for Backend to start
        run: |
          sleep 10

      - name: "npm install Frontend"
        run: |
          cd ./frontend
          npm install

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: ./frontend
          start: npm start
          wait-on: 'http://localhost:3000'

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Build Image
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          load: true
          tags: ${{ env.FRONTEND_TAG }}